apiVersion: v1
kind: Service
metadata:
  name: recipe-svc
  # namespace: terrestrial-platform
spec:
  selector:
    app: recipe-app
  ports:
    - protocol: "TCP"
      port: 9099
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-app
spec:
  selector:
    matchLabels:
      app: recipe-app
  replicas: 1
  template:
    metadata:
      labels:
        app: recipe-app
    spec:
      containers:
        - name: recipe-app
          image: savantripathi22/recipe:june22
          imagePullPolicy: Always
          ports:
            - containerPort: 9099

